### ISSUE TITLE
Decide on Feature Set

### ISSUE THREAD

**Issue by prowe214** [Skookum/stumbl-2019#1]
## Issue Type (Feature, Bug, Discussion)
Discussion

## Description

As a team, we should develop an exhaustive list of the features we would like to incorporate into the application.

- Core features
- Nice-to-have features

## Dependencies (What does this depend on)

- None

## Dependents (What depends on this being completed)

- Design
- Everything

## Suggested resolution

- Meeting or poll on deciding core features and nixing any ideas we don't want to build
- List the decided features in the root README

**Comment by prowe214** [comment]
Feature set document has been [posted to the wiki](https://github.com/Skookum/stumbl-2019/wiki/Feature-Set) for approval by the team.

**Comment by chrisman** [comment]
Dump of features from meeting with DSW. To be added to the wiki.

- **Registration**: Is it possible to integrate with DSW registration system? i.e. have users sign in with their DSW username/password? (All DSW participants *must* have registered with DSW) (this is probably a no?)

- **Check in requirements**? Simple geolocation check-in? post a selfie? (<--security/privacy concern) QR Codes? 

- **Job postings** for participating companies. Possibly job postings ONLY for Sponsoring Companies. (<---data modeling implications)

- **Multiple events**! Big one, and this is likely to be a real requirement. Be able to support multiple events. Most likely Tuesday and Thursday.

    Implications:
    - Don't show the event before it is time
    - Will the Tuesday event _continue_ on Thursday? i.e. the user continues to collect checkins for a grand total of `tuesday + thursday` number of checkins? Or are they discreet, unrelated events

**Comment by prowe214** [comment]
Documented DSW's feature requests on the wiki page [Feature Set](https://github.com/Skookum/stumbl-2019/wiki/Feature-Set).  Closing, will reopen new issue if the partnership blossoms.
