### ISSUE TITLE
🗣 abandon git-flow?

### ISSUE THREAD

**Issue by chrisman** [Skookum/stumbl-2019#11]
DISCUSSION TIME 🗣💬🕔

How is `git flow` working out for you? It's been a little clunky so far for me. This discussion is about whether or not to:

-  👍 proceed with using it, or 

- 👎 keep using the *strategy* on a kind of honor system, but ditch the CLI tool

**Comment by chrisman** [comment]
i'm not ready to vote on this yet, but I want to create a space to talk about it.

My experience so far:

1. `git flow feature start 8-add-pull-request-template` or whatever.  (It's kind of verbose! If we keep using I'm going to need to create some new git aliases.)

2. start working. looks good. be done working.

3. **first breaking part of `git flow`:** `git flow feature finish 8-add-pull-request-template`.

    This breaks our git flow. This merges the feature branch into develop and deletes this feature branch. This is bad because Develop is protected: you cannot push to it. (Which is a Good Thing; we want code reviews and PR approval)

4. Damn. Okay, branch off Develop back into a newly, freshly created `8-add-pull-request-template`.

5. Back to Develop. `git reset --hard HEAD^`

6. Back to feature branch. Push. Open PR

7. ???

So half of `git-flow` is unusable. The merge-branch and delete-branch part. I still like its enforced namespacing of branches though. But again I'm not sure if its achieving Maximum Awesomeness here.

**Comment by prowe214** [comment]
Yeah I'm down for changing to an adjusted `git flow`.  Basically, master and develop are still protected, we open new branches using the pattern `feature/*` off of `develop`, and hotfix branches (we won't have to deal with these until like July) are handled manually off of master and merged back into develop and master.

Basically, we don't push to master until we are comfortable with develop, and all other branches are created using the git flow prefixes but using the normal github strategy.  I've used this successfully before.

**Comment by prowe214** [comment]
Conclusion: We will leverage a modified git flow. 

Branches will follow the same naming scheme, and will merge to develop.  We will then merge develop into master at stable release points.

Closing.
