### ISSUE TITLE
🗣Transition to monorepo?

### ISSUE THREAD

**Issue by chrisman** [Skookum/stumbl-2019#13]
## Question

Should we move the front-end and the back-end into a single monorepo?

## Pros and cons

Benefits include:

- simple docker management of the project

- reduced cognitive overhead / simplicity of having everything in place

Cons include:

- having to do the work of setting up the project

## Discus and vote

Comment below your questions and concerns. Emote here (thumbs up/thumbs down) to cast your vote.

**Comment by chrisman** [comment]
I'm not sure how complicated managing workspaces will be, but I know that Yarn has [native support for workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) (which, if we want to use that, would require transitioning the project to yarn)

otherwise, I think [lerna](https://github.com/lerna/lerna) is the standard in NPM land.

and mind you, that's all based on what I've experienced when working on projects with multiple JS packages. It might not be necessary at all with a JS + Go project.

**Comment by prowe214** [comment]
Closing as we are now managing the back end in a separate repository
