### ISSUE TITLE
🚀Back End environments setup

### ISSUE THREAD

**Issue by prowe214** [Skookum/stumbl-2019#16]
**Is your feature request related to a problem? Please describe.**
We require deployment environments to build, test, and ultimately deliver our product to users.

**Describe the solution you'd like**
- Decision on AWS / GCP
- Set up accounts 
- Begin wiring up a basic back end

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by chrisman** [comment]
move discussion to https://github.com/Skookum/stmbl-api and close issue?

**Comment by prowe214** [comment]
Agreed with @chrisman .  Closing...
