### ISSUE TITLE
🚀Notifications for discussions in Github Issues stink 👎

### ISSUE THREAD

**Issue by prowe214** [Skookum/stumbl-2019#18]
**Is your feature request related to a problem? Please describe.**
We have successfully been centralizing discussions in Github Issues, but notifications for these discussions are only delivered via email (which all of us admittedly rarely check).  We can figure out a way to be notified better so we communicate more effectively.

**Describe the solution you'd like**
Slack notifications to a shared channel for new posts on any issues

**Describe alternatives you've considered**
- Zapier email parser to send github emails to slack (I've successfully done this for myself in the past)
- Github integration that we haven't explored?

**Additional context**
We want to have these conversations documented on the repo itself, so saying "Just talk about it in slack" is not a solution here.

**Comment by chrisman** [comment]
I wasn't even "watching" this repo until just now so I wasn't even getting email notifications 😆 

With respect and friendliness:
Is it possible that this is a personal issue? If you're getting updates to your email and you aren't checking your email, then possibly you need to figure out how to manage your email? maybe set a filter for emails for this repo that sends that email to your main inbox so you get a notification?
