### ISSUE TITLE
🚀Remove Cypress, Jest

### ISSUE THREAD

**Issue by prowe214** [Skookum/stumbl-2019#32]
**Is your feature request related to a problem? Please describe.**
Our builds are delayed by Vue's inclusion of Cypress.  

**Describe the solution you'd like**
I don't think we'll have time to be building e2e tests, so removing Cypress from the build should be acceptable.  If we don't have plans to implement Jest tests, we could also remove that.

**Describe alternatives you've considered**
Removing cypress and leaving Jest in case we want to implement those later.

**Comment by chrisman** [comment]
cypress is a huge dep. +1 to removing it.
and I guess if we're not going to unit test anything, Jest should go to. we can always add it back.

**Comment by chrisman** [comment]
I'll take this. And will wait for #31 to be merged in first since they both mess with package.json and package-lock.json.
